export default {
    linea: {
        meUSDC: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
        meUSDT: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
        meWETH: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000000000000000",
            collateralFactor: "0.7",
            reserveFactor: "0.15",
            rateModel: "MediumRateModel",
        },
    },
    linea_goerli: {
        meUSDC: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
        meUSDT: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
        meWETH: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000000000000000",
            collateralFactor: "0.7",
            reserveFactor: "0.15",
            rateModel: "MediumRateModel",
        },
    },
    omni_testnet: {
        meWOMNI: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000000000000000",
            collateralFactor: "0.7",
            reserveFactor: "0.15",
            rateModel: "VolatileRateModel",
        },
        meUSDC: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000000000000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
        meUSDT: {
            source: "",
            priceFeed: "",
            priceDecimals: "",
            baseUnit: "1000000000000000000",
            collateralFactor: "0.8",
            reserveFactor: "0.13",
            rateModel: "StableRateModel",
        },
    },
} as const;
